name: Lengbanlist
version: 1.6.3
main: org.leng.Lengbanlist
commands:
  lban:
    description: 主命令
    usage: /<command> <子命令> [参数]
  report:
    description: 举报命令
    usage: /<command> <玩家名/子命令> [原因/参数]
  admin:
    description: 管理员命令
    usage: /<command> <子命令> [参数]
  check:
    description: 检查命令
    usage: /<command> <玩家名/IP>
  language:
    description: 语言选择命令
    usage: /<command>
  ban:
    description: 封禁玩家命令
    usage: /<command> <玩家名/IP> [时间] [原因]
  unban:
    description: 解除封禁命令
    usage: /<command> <玩家名/IP>
  mute:
    description: 禁言玩家命令
    usage: /<command> <玩家名> [原因]
  unmute:
    description: 解除禁言命令
    usage: /<command> <玩家名>
  warn:
    description: 警告玩家命令
    usage: /<command> <玩家名> [原因]
  unwarn:
    description: 移除警告命令
    usage: /<command> <玩家名>
  add:
    description: 添加封禁命令
    usage: /<command> <玩家名/IP> <时间> <原因>
  remove:
    description: 移除封禁命令
    usage: /<command> <玩家名/IP>