version: 2.1

jobs:
  build:
    docker:
      - image: eclipse-temurin:17-jdk  # 使用 Adoptium (原 AdoptOpenJDK) 的 Java 17
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package
          working_directory: "Lengbanlist - main"  # 进入你的 Maven 项目目录
      - store_artifacts:
          path: "Lengbanlist - main/target/"
          destination: artifacts  # 存储构建产物

  test:
    docker:
      - image: eclipse-temurin:17-jdk
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn test
          working_directory: "Lengbanlist - main"
      - store_test_results:
          path: "Lengbanlist - main/target/surefire-reports"  # 存储测试报告

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
